server.port=9090

spring.cloud.gateway.routes[0].id=product-service
spring.cloud.gateway.routes[0].uri=lb://PRODUCT
spring.cloud.gateway.routes[0].predicates[0]=Path=/products/**

spring.cloud.gateway.routes[1].id=product-catalogue-service
spring.cloud.gateway.routes[1].uri=lb://PRODUCTCATALOGUE
spring.cloud.gateway.routes[1].predicates[0]=Path=/catalogs/**

spring.cloud.gateway.routes[2].id=product-stock-service
spring.cloud.gateway.routes[2].uri=lb://PRODUCTSTOCK
spring.cloud.gateway.routes[2].predicates[0]=Path=/inventory/**

spring.cloud.gateway.routes[3].id=product-price-service
spring.cloud.gateway.routes[3].uri=lb://PRODUCTPRICE
spring.cloud.gateway.routes[3].predicates[0]=Path=/prices/**

spring.cloud.gateway.routes[4].id=cart-service
spring.cloud.gateway.routes[4].uri=lb://CART
spring.cloud.gateway.routes[4].predicates[0]=Path=/carts/**

spring.cloud.gateway.routes[5].id=recommendation-service
spring.cloud.gateway.routes[5].uri=lb://RECOMMENDATION
spring.cloud.gateway.routes[5].predicates[0]=Path=/recommendations/**
